#!/bin/bash

# Flutter Friends Circle Project - Environment Check Script
# Usage: ./check_env.sh

# Color definitions
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
NC='\033[0m'

echo -e "${PURPLE}Flutter Friends Circle Project Environment Check${NC}"
echo -e "${PURPLE}================================================${NC}"

READY=true

# Check JDK
echo -e "\n${BLUE}JDK Check${NC}"
if command -v java >/dev/null 2>&1; then
    JAVA_VER=$(java -version 2>&1 | head -1)
    echo -e "${GREEN}  JDK installed: ${JAVA_VER}${NC}"
    if java -version 2>&1 | grep -q '"17\.\|"21\.'; then
        echo -e "${GREEN}  JDK version OK (17+)${NC}"
    else
        echo -e "${YELLOW}  JDK 17+ recommended for Gradle builds${NC}"
    fi
else
    echo -e "${RED}  JDK not installed${NC}"
    echo -e "${YELLOW}   Install JDK 17: brew install openjdk@17${NC}"
    READY=false
fi

# Check Android SDK
echo -e "\n${BLUE}Android SDK Check${NC}"
if [ -n "$ANDROID_HOME" ] || [ -n "$ANDROID_SDK_ROOT" ]; then
    SDK_PATH="${ANDROID_HOME:-$ANDROID_SDK_ROOT}"
    echo -e "${GREEN}  Android SDK found: ${SDK_PATH}${NC}"
else
    echo -e "${YELLOW}  ANDROID_HOME / ANDROID_SDK_ROOT not set${NC}"
    if [ -d "$HOME/Library/Android/sdk" ]; then
        echo -e "${GREEN}  Found SDK at default location: ~/Library/Android/sdk${NC}"
    elif [ -d "$HOME/Android/Sdk" ]; then
        echo -e "${GREEN}  Found SDK at default location: ~/Android/Sdk${NC}"
    else
        echo -e "${RED}  Android SDK not found${NC}"
        READY=false
    fi
fi

# Check ADB
echo -e "\n${BLUE}ADB Check${NC}"
if command -v adb >/dev/null 2>&1; then
    echo -e "${GREEN}  ADB installed: $(adb version | head -1)${NC}"
else
    echo -e "${RED}  ADB not installed or not in PATH${NC}"
    READY=false
fi

# Check FVM
echo -e "\n${BLUE}FVM Check${NC}"
if command -v fvm >/dev/null 2>&1; then
    echo -e "${GREEN}  FVM installed: $(fvm --version)${NC}"
else
    echo -e "${RED}  FVM not installed${NC}"
    echo -e "${YELLOW}   Install: dart pub global activate fvm${NC}"
    READY=false
fi

# Check Flutter versions via FVM
echo -e "\n${BLUE}Flutter Version Check${NC}"
if command -v fvm >/dev/null 2>&1; then
    echo "Installed Flutter versions:"
    fvm list
else
    echo -e "${RED}  Cannot check, FVM not installed${NC}"
fi

# Check project configuration for all 6 variants
echo -e "\n${BLUE}Project Configuration Check${NC}"

VARIANTS=("3.19_SurfaceView" "3.19_TextureView" "3.27_SurfaceView" "3.27_TextureView" "3.29_SurfaceView" "3.29_TextureView")

for VARIANT in "${VARIANTS[@]}"; do
    if [ -d "$VARIANT" ]; then
        # Check for FVM config (.fvmrc or .fvm/fvm_config.json)
        if [ -f "$VARIANT/.fvmrc" ] || [ -f "$VARIANT/.fvm/fvm_config.json" ]; then
            echo -e "${GREEN}  $VARIANT: FVM config found${NC}"
        else
            echo -e "${RED}  $VARIANT: FVM config missing${NC}"
            READY=false
        fi
        # Check lib/ symlink points to shared source
        if [ -L "$VARIANT/lib" ] && [ -d "$VARIANT/lib" ]; then
            echo -e "${GREEN}  $VARIANT: lib/ symlink OK (-> $(readlink "$VARIANT/lib"))${NC}"
        elif [ -d "$VARIANT/lib" ]; then
            echo -e "${YELLOW}  $VARIANT: lib/ is a directory (not symlinked to shared/)${NC}"
        else
            echo -e "${RED}  $VARIANT: lib/ missing${NC}"
            READY=false
        fi
    else
        echo -e "${RED}  $VARIANT: directory not found${NC}"
        READY=false
    fi
done

# Check shared directory
if [ -d "shared/lib" ]; then
    SHARED_FILES=$(find shared/lib -name "*.dart" 2>/dev/null | wc -l | tr -d ' ')
    echo -e "${GREEN}  shared/lib: ${SHARED_FILES} Dart files${NC}"
else
    echo -e "${RED}  shared/lib: directory not found${NC}"
    READY=false
fi

# Check Android devices
echo -e "\n${BLUE}Android Device Check${NC}"
if command -v adb >/dev/null 2>&1; then
    DEVICES=$(adb devices 2>/dev/null | grep -w "device$" | wc -l)
    if [ "$DEVICES" -gt 0 ]; then
        echo -e "${GREEN}  Detected $DEVICES Android device(s)${NC}"
        adb devices
    else
        echo -e "${YELLOW}  No Android devices detected${NC}"
        echo -e "${YELLOW}   Please ensure device is connected and USB debugging is enabled${NC}"
    fi
else
    echo -e "${RED}  ADB not available${NC}"
fi

# Check build scripts
echo -e "\n${BLUE}Build Script Check${NC}"
if [ -x "build_release.sh" ]; then
    echo -e "${GREEN}  build_release.sh executable${NC}"
else
    if [ -f "build_release.sh" ]; then
        echo -e "${YELLOW}  build_release.sh exists but not executable${NC}"
        echo -e "${YELLOW}   Run: chmod +x build_release.sh${NC}"
    else
        echo -e "${RED}  build_release.sh not found${NC}"
    fi
    READY=false
fi

if [ -x "install_apks.sh" ]; then
    echo -e "${GREEN}  install_apks.sh executable${NC}"
else
    echo -e "${YELLOW}  install_apks.sh not found or not executable (will be generated by build_release.sh)${NC}"
fi

# Check output directory
echo -e "\n${BLUE}Output Directory Check${NC}"
if [ -d "apk-release" ]; then
    APK_COUNT=$(find apk-release -name "*.apk" 2>/dev/null | wc -l)
    echo -e "${GREEN}  apk-release/ directory exists, contains ${APK_COUNT} APK file(s)${NC}"
    if [ "$APK_COUNT" -gt 0 ]; then
        echo "Recent APK files:"
        ls -lt apk-release/*.apk 2>/dev/null | head -6
    fi
else
    echo -e "${YELLOW}  apk-release/ directory does not exist, will be created during build${NC}"
fi

# Summary
echo -e "\n${PURPLE}Environment Check Summary${NC}"
echo -e "${PURPLE}=============================${NC}"

if $READY; then
    echo -e "${GREEN}Environment check passed! Ready to build APKs${NC}"
    echo -e "\n${BLUE}Build command:${NC}"
    echo -e "${YELLOW}   ./build_release.sh${NC}"
else
    echo -e "${RED}Environment issues found, please fix according to suggestions above${NC}"
fi
